### ISSUE TITLE
NSManagedObjectContextObjectsDidChangeNotification don't work with callMethodWithName

### ISSUE THREAD

**Issue by chrisscholly** [martijnwalraven/meteor-ios#101]
Hi,
Seems that I can't be notified with `NSManagedObjectContextObjectsDidChangeNotification` when I use `callMethodWithName` to perform Mongo update. The update is done locally, no problem, but I don't receive the notification.
Example:

``` javascript
// server side
updateLoginCreatedAt: ->
    Meteor.users.update {_id: Meteor.userId()}, {$set: {'createdAt': new Date()}}
```

``` Swift
// iOS side
func someFunc() {
    NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(objectsDidChange), name: NSManagedObjectContextObjectsDidChangeNotification, object: Meteor.mainQueueManagedObjectContext)
    Meteor.callMethodWithName("updateLoginCreatedAt", parameters: nil) { result, error in
        print("updateLoginCreatedAt done!")
    }
}
func objectsDidChange(notification: NSNotification) {
    print("Changed!")
}
```

``` Swift
// Result
updateLoginCreatedAt done!

// Expected result
updateLoginCreatedAt done!
Changed!
```

Thanks in advance for your help :)

**Comment by martijnwalraven** [comment]
I think `NSManagedObjectContextObjectsDidChangeNotification` only works for objects that have been previously fetched in the managed object context.

This has been a while, but you may have more luck observing `NSManagedObjectContextDidSaveNotification`.

**Comment by chrisscholly** [comment]
Thank you for your answer!

Have tried observing `NSManagedObjectContextDidSaveNotification` but this is the same result :(

**Comment by chrisscholly** [comment]
`METDatabaseDidChangeNotification` seems to work better. 

Currently I use Core Data to fetch data and `METDatabaseDidChangeNotification` to observe changes. 
I'm guessing there's no problem to fetch new data from Core Data when a `METDatabaseDidChangeNotification` is fired. Does it make sense?

**Comment by martijnwalraven** [comment]
Yep, that makes sense.

**Comment by chrisscholly** [comment]
Thank you guy! 👍🏻
