### ISSUE TITLE
Object not being sent to server

### ISSUE THREAD

**Issue by gazzer82** [martijnwalraven/meteor-ios#11]
Hi,

I am trying to create a test object locally in swift and send it to my Meteor server, whilst i am getting no errors i'm also not seeing the object appear on the server.

I am setting meteor-ios up as follows:

    let Meteor = METCoreDataDDPClient(serverURL: NSURL(string: "wss://localhost/websocket"))

```
    func startMeteor () {
        Meteor.connect()
        let subscriptionLoader = SubscriptionLoader()
        subscriptionLoader.addSubscriptionWithName("Tasks")
        
        subscriptionLoader.whenReady {
            //self.fetchedResultsController.performFetch()
        }
        
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "objectsDidChange:", name: NSManagedObjectContextObjectsDidChangeNotification, object: managedObjectContext)
    }

```

To which i get a successful connected message, i am then trying to create an object using the following, for which i get a successful notification from core data, but nothing appear in Mongo/Meteor, i'm obviously missing something here so help greatly appreciated!

```
    @IBAction func createTask(sender: UIButton) {
        let managedObjectContext = Meteor.mainQueueManagedObjectContext
        
        let task = NSEntityDescription.insertNewObjectForEntityForName("Tasks", inManagedObjectContext:managedObjectContext) as Tasks
        task.text = "Test Text"
        
        var error: NSError?
        if !managedObjectContext.save(&error) {
            println("Encountered error saving objects: \(error)")
        }
    
    }
```

Thanks

Gareth

**Comment by martijnwalraven** [comment]
Do you encounter any errors? Did you configure the Core Data model and set up the tasks collection on the server?

**Comment by gazzer82** [comment]
No errors at all on iOS in the console or on the server, core data is setup in the sense that the model and class have been created and seem to be functioning. When I create a new object I get all the appropriate callbacks from core data. But those object never appear in Meteor, plus the meteor object never appear in core data. 

Do I need to do anything more than I have done in my code to setup the sync, or anything else I need to do to the core data model to associate it with the collection in Meteor?

Thanks

Gareth

**Comment by martijnwalraven** [comment]
From the code you posted, it seems you've named your entity 'Tasks'. Entity names are usually singular and the framework uses an automatic singular-plural name mapping a la Rails to generate a default collection name. Alternatively, you can specify a collectionName property as userInfo in the model editor.

Let me know if this helps. I'm a bit surprised there are no errors, so I should probably look into this and improve error reporting.
