### ISSUE TITLE
Core Data Questions

### ISSUE THREAD

**Issue by ccorcos** [martijnwalraven/meteor-ios#13]
I'm trying to get a better understanding of how MongoDB, subscriptions, and Core Data all work together (I've worked with iOS before but I'm no expert). 

Its my understanding that when you create a subscription, (somehow) it all ends up in Core Data with the right relationship connections. When you edit, insert, or remove a managedObject in a managedObjectContext and save that context, then an appropriate update is sent to the server all under the hood.

So my question here is how all the correct relationships end up in Core Data. Does it simply use the name of the key, i.e. listId means it points to a list? Or do we have to manually set all this stuff somewhere?  Also, when you create a new subscription and data starts coming, how do you know which managed object the document applies to?

Great package by the way.

Thanks

**Comment by martijnwalraven** [comment]
Relationships in Core Data are indeed mapped automatically based on the relationship name (although it is possible to specify a custom fieldName).

When you perform a subscription request, the server sends DDP messages that result in documents getting stored in the local cache. It will also notify you when the subscription is ready, when data for all documents that match the subscription have been sent.

The way Meteor works, there is no way to know which documents were sent as a result of which subscription. The server keeps track of which documents (and which fields) have been requested to date and only sends data to the client if it hasn't been sent before.

This means both with a regular Meteor JavaScript client and with Core Data you have to perform an explicit query. So if you subscribe to 'books with a title that starts with a' for example, you would still need to query for 'books with a title that starts with a'.

I hope this makes sense. Let me know if you have more questions.

**Comment by ccorcos** [comment]
Hmm. So let me clarify with some yes/no questions:

1. When I subscribe from iOS, the documents are automatically translated into their respective Core Data entities.

2. When I change a Core Data managedObject and save the context, that document is also updated on the server.

**Comment by martijnwalraven** [comment]
Yes to both, mostly. Translation to managed objects (1) doesn't happen until you perform a Core Data fetch. As for (2), an update request could fail on the server (e.g. because of an authorization failure) and that would lead to a rollback of the change on the client.

**Comment by ccorcos** [comment]
Ahh so this is what you're saying here:

> The way Core Data fetching has been implemented is fairly naive and although usable seems really inefficient. All documents in a given collection are instantiated as NSManagedObjects before a predicate and sortDescriptors are applied. At least some of this work should be offloaded to the local cache, so we only have to perform further processing on a subset of objects. This isn't easy however, if we want to support predicates referring to relationships at the model level.

So once you use a predicate to fetch from Core Data, then it will take the appropriate documents from local storage.

3. When you unsubscribe, I'm assuming this will also clean up your Core Data managedObjects, right?

**Comment by martijnwalraven** [comment]
Yes, unsubscribing leads to documents being removed from the local cache which maps to deleted objects in Core Data (and this would of course also result in an NSManagedObjectContextObjectsDidChangeNotification with the deleted object IDs).

What I meant by the bit above is more subtle: fetching a subset of entities using a predicate currently instantiates managed objects for all documents in the mapped collection. The predicate is then used to filter the objects and only the resulting subset is returned. Managed objects that do not match the predicate are immediately released, but it is still inefficient to instantiate them first (and for every fetch).

The release of React Native has given me some fresh ideas and I'm considering running minimingo in a JavaScriptCore context instead of keeping the local cache in Objective-C. This would have the benefit of allowing the use of Mongo selectors to perform queries at the document level. But I would have to translate relationship keypaths in predicates to selectors.

**Comment by ccorcos** [comment]
Hmm. Why aren't documents immediately processed into CoreData rather than sitting in local storage until a predicate?

I like React Native and what they're trying to do, but I think you have a very nice package here. I think there is a huge benefit to using all the underlying infrastructure of iOS. For example, with Core Data, you can undo and redo (does that work with updating the server?) and you can hook up UITableViews easier as well.

**Comment by martijnwalraven** [comment]
Well, it depends on what you mean by being processed into Core Data. Conceptually, all documents exist as managed objects, just as they exist for all rows in a database when you use SQLite storage. But they are only instantiated (bound to a specific context) when fetched. This is just how Core Data works. You still need a place to store the data.

Also, I wanted to keep open the possibility of avoiding Core Data (either completely or for parts of an app) and performing operations directly at the document level (see 
https://github.com/martijnwalraven/meteor-ios/wiki/Usage-without-Core-Data).

Integrating with iOS mechanism like Core Data definitely has its benefits over React Native. Out of the top of my head, undo and redo should work if it just makes changes to the context and saves these.

**Comment by ccorcos** [comment]
Hmm. What do you see as the main benefit of losing CoreData?
