### ISSUE TITLE
Server side code for meteor-ios-todos example 

### ISSUE THREAD

**Issue by lukya** [martijnwalraven/meteor-ios#15]
Can you upload js, html and css for your version of the todos example?
I am a beginner trying to implement meteor-ios with CoreData in one of my existing apps.
I need to set up the server environment and mongo db as per my iOS app.
It would be really great if i could run your version of todos code locally and compare the database to my code data model.

**Comment by martijnwalraven** [comment]
It's using the default version of the Todos example. You can install it locally with:
```
meteor create --example todos
```

**Comment by lukya** [comment]
I did create the default 'ToDo' list in the tutorial but not the example todos.  
Sorry for the silly question. Closing the issue.
