### ISSUE TITLE
METDDPConnection.h included as project header, needs to be public.

### ISSUE THREAD

**Issue by lukya** [martijnwalraven/meteor-ios#16]
I need to initialise METCoreDataDDPClient using an existing managed object context.
I am trying to use `initWithConnection: managedObjectModel:` but i am not able to create `METDDPConnection` instance because METDDPConnection.h is included as a project header.
Is there a specific reason you have not exposed METDDPConnection or have i misunderstood the intended purpose of the initialiser?
If not, is it ok to include it METDDPConnection.h as a public header?

**Comment by martijnwalraven** [comment]
That initializer is only used in tests, where it is passed a mock connection. I'm not sure what you mean when you say you want to use an existing managed object context. METCoreDataDDPClient sets up its own Core Data stack (with METIncrementalStore). Although you can set this up manually (without using METCoreDataDDPClient), there is usually no need.

If what you're saying is you need another context besides mainQueueManagedObjectContext, you could create these yourself by subclassing METCoreDataDDPClient (don't forget to merge changes, etc.).

**Comment by lukya** [comment]
I am trying to get an older, standalone app to sync with a new meteor instance on the server.
This app has a complex model and i want the DDP connection to initially upload existing data and then continue to sync changes to and form app's context (pointing to the same persistent store). 

I understand that i'll need to go through a lot of customisation and a even more tedious work on the server/meteor side to get this working. 

Do you think this is  not possible or see any big disadvantages of exposing the connection and other classes?

Your help and prompt replies are highly appreciated.

Thank you.

**Comment by martijnwalraven** [comment]
I have no problem exposing METDDPConnection, but I don't think that'll help you in this particular situation.

The Core Data integration will only work when used with its own persistent store (METIncrementalStore). The store simply acts as an interface to the in memory collections, and doesn't offer any storage itself. There is no real offline functionality, and connecting to the server will transfer all requested data anew each time. This is why you use subscriptions to only receive data you're interested in.

If you want to upload data from a standard SQLite persistent store, you'll have to create two Core Data stacks and transfer objects manually from the standard store to the Meteor iOS store (they could use the same managed object model). This would create the data in mongodb on the server. You could then remove the SQLite store and from then on only use the Meteor iOS store to connect to the server.

In the future, I might look into implementing real offline functionality but doing that right requires changes to the DDP protocol.

**Comment by tonyxiao** [comment]
Does Meteor use local storage to cache documents? I remember somewhere that meteor has some kind of offline capability of its own.
