### ISSUE TITLE
React Native Bridge?

### ISSUE THREAD

**Issue by fardeemmunir** [martijnwalraven/meteor-ios#19]
Any plans on having a react native bridge so people can write IOS apps with all the JS goodness.

**Comment by martijnwalraven** [comment]
I can't make any promises, and I'm not sure about the right approach yet, but this is something I'm looking into right now.

**Comment by fardeemmunir** [comment]
It would be tricky I guess since the library also needs a Core Data bridge. Or you could take a different approach for storing stuff in the cache.

**Comment by martijnwalraven** [comment]
I don't think it makes sense to use Core Data from JavaScript. But there is already a separate document cache where the data is stored.

**Comment by smothers** [comment]
:+1: 

Any new thoughts around what this bridge extension might look like? Is CoreData required for latency compensation?
