### ISSUE TITLE
meteor _id and ios entity attributes

### ISSUE THREAD

**Issue by trevorbroad** [martijnwalraven/meteor-ios#2]
Hey,

First off, awesome work! This is a huge help in my project.

I'm trying to fetch a record using the meteor auto-generated '_id', but I can't add the same attribute to the corresponding Core Data entity because it won't allow me to start an attribute with anything other than a letter. Is there a graceful solution to this?

**Comment by martijnwalraven** [comment]
Good to hear you're finding it useful, even without decent documentation! Are you using it from Swift or Objective-C?

The `_id`- field is actually used to construct the Core Data objectID. `METCoreDataDDPClient` exposes  `objectIDForDocumentKey:` that you can use to get from a key (a combination of collection name and documentID) to an `NSManagedObjectID`:

``` Objective-C
NSManagedObjectID *objectID = [client objectIDForDocumentKey:[METDocumentKey keyWithCollectionName:@"todos" documentID:@"bla"]];
NSManagedObject *object = [managedObjectContext objectWithID:objectID];
```

I'm still working out the API, so consider this a temporary solution. What is your intended usage pattern here? Where does the `_id` value come from?

**Comment by trevorbroad** [comment]
It is pretty difficult without docs, I'm also new to iOS development so the difficulty is compounded, I'm basically muddling through. Do you have a swift example? I'm just trying to lookup an existing object and update some values.

**Comment by martijnwalraven** [comment]
I can imagine the difficulty! Hopefully I'll find some time over the next few weeks to work on the documentation and maybe even write a tutorial. I'm in the middle of a deadline for a project and the API is still in a bit of a flux, so it'll be a while before things get stable. Core Data in itself isn't very user friendly, so I'm also working on some helper classes and extensions in Swift to make things easier.

This should work for now:
``` Swift
let objectID = Meteor.objectIDForDocumentKey(METDocumentKey(collectionName: "todos", documentID: "bla"))
let object = managedObjectContext.objectWithID(objectID)
```

**Comment by trevorbroad** [comment]
That's great, worked for me, thanks!

**Comment by trevorbroad** [comment]
Hey again, I'm now looking for a way to get the meteor ID of an object I've created. Essentially, I'm creating an object, then creating related objects and need to add the ID of the original object to the related ones. How can I get the ID of an object I already have in the managed object?

**Comment by martijnwalraven** [comment]
I'm planning on simplifying this, but right now you can get the document ID of an object by using:
```
let object: NSManagedObject = ...
let documentID = Meteor.documentKeyForObjectID(object.objectID).documentID
```
I'm not sure how you're setting up relationships, but in most cases it shouldn't be necessary to connect objects manually by ID. If you define a relationship in your Core Data model and set its value, a field with the related document ID (or array of document IDs) will be managed for you.

**Comment by trevorbroad** [comment]
That would be better, can you point me to the place in your Todos example where I can get a sense of how to make that connection? I did some setup to relationships in the Core Data model, but I must be missing something because its not adding the IDs for me

**Comment by martijnwalraven** [comment]
It should work with any properly set up Core Data relationship. There is no additional code required, you simply define the relationship in the managed object model. The only issue to keep in mind is that by default it will add IDs on both sides of the relationship. You'll have to specify 'storage = false' as user info on one of the relationship sides to suppress this (for many-to-many you need both sides).

Here are two screenshots from the Todos example:

![screen shot 2015-02-17 at 07 34 04](https://cloud.githubusercontent.com/assets/54485/6224167/e8415a62-b677-11e4-9755-776bea0af069.png)

![screen shot 2015-02-17 at 07 34 24](https://cloud.githubusercontent.com/assets/54485/6224170/f172a5be-b677-11e4-9bad-7796b2141355.png)

**Comment by trevorbroad** [comment]
I have it setup essentially the same as in the screens, but it doesn't seem to be adding the values automatically. To be clear, I'm looking to have the MongoDB '_id' field for the List object inserted into the todo object as a new field on creation. Is that what should be happening?

**Comment by martijnwalraven** [comment]
Yes, if you set `todo.list` to a List object, a `listId` field with the list `_id` value should be inserted automatically into the todo document. Are you sure you're setting the list property? And have you defined it as a managed property in the Todo class?
```
@NSManaged var list: List!
```

**Comment by trevorbroad** [comment]
ah yes! I was trying to add it manually as a new field, but this is much better. Thanks!
