### ISSUE TITLE
InflectorKit.framework not found

### ISSUE THREAD

**Issue by thatjuan** [martijnwalraven/meteor-ios#26]
After installing meteor-ios with Carthage and running my app, I get this runtime error:

dyld: Library not loaded: @rpath/InflectorKit.framework/InflectorKit
  Referenced from: [...].app/Frameworks/Meteor.framework/Meteor
  Reason: image not found

I assume it's referring to a dependency to https://github.com/mattt/InflectorKit

**Comment by justinmakaila** [comment]
This should be closed with #27

**Comment by romeocodemagnus** [comment]
I cloned July 7, 2015, run the Todos iOS code and got the same error. Please help.

**Comment by justinmakaila** [comment]
Did you run `carthage update`?
