### ISSUE TITLE
Access mongo id?

### ISSUE THREAD

**Issue by justinmakaila** [martijnwalraven/meteor-ios#37]
Is there a way to access the mongo id of an object saved in CoreData? Can this be accomplished by adding a `fieldName` mapping to `userInfo` of the `NSManagedObject`?

**Comment by pozylon** [comment]
Hi Justin, you can use Meteor.documentKeyForObjectID: documentID

**Comment by justinmakaila** [comment]
I was trying to avoid having to make that call manually, and adding it to my model explicitly causes a CoreData error... 

Thanks.
