### ISSUE TITLE
No user data

### ISSUE THREAD

**Issue by callmeahab** [martijnwalraven/meteor-ios#47]
When subscribing to users collection i receive no data for users.

I'm using `FetchedResultsTableViewController` class from the example.
Configuring subscription loader with:
```swift
override func configureSubscriptionLoader(subscriptionLoader: SubscriptionLoader) {
    subscriptionLoader.addSubscriptionWithName("users")
}
```

On the server side i publish users data with:
```javascript
Meteor.publish("users", function(){
  return Meteor.users.find({}, {fields: {emails: 1, profile: 1}});
});
```

But when i log data received on client i get:
```
<Circuit.User: 0x7f9216050650> (entity: User; id: 0x7f9213c21750 <x-coredata://21A947C1-FE9A-4828-A450-031F2E7249F0-80740-00009D910A641498/User/pjk5LMRygJSwCuBKzn> ; data: {
    createdAt = nil;
    emailAddresses = nil;
    items = nil;
    name = nil;
    profile = nil;
    services = nil;
})
<Circuit.User: 0x7f92160482d0> (entity: User; id: 0x7f9213c88f50 <x-coredata://21A947C1-FE9A-4828-A450-031F2E7249F0-80740-00009D910A641498/User/pP3dxmjoXD5mTedfXa> ; data: {
    createdAt = nil;
    emailAddresses = nil;
    items = nil;
    name = nil;
    profile = nil;
    services = nil;
})
```

This is my user class:
```swift
import CoreData

class User: NSManagedObject {
    typealias NamedValues = [String:AnyObject]

    @NSManaged var createdAt: NSDate?
    @NSManaged var name: String?
    @NSManaged var items: NSSet!
    
    @NSManaged var emailAddresses: [NamedValues]?
    var emailAddress: String? {
        return emailAddresses?.first?["address"] as? String
    }
    
    @NSManaged var profile: NamedValues?
    @NSManaged var services: NamedValues?
}
```

I get similar results with `currentUser` function from `FetchedResultsTableViewController`

Thanks

**Comment by callmeahab** [comment]
Ok. I figured it out, it was a dumb mistake on my part, I was publishing `emails` but had `emailAddresses` field on core data model.

Before closing this issue I'd like to ask if there's a way of sending parameters during user creation, for instance i would like to create an empty array of items on user creation etc.

**Comment by martijnwalraven** [comment]
Good to hear you figured out what the problem was.

As for your question, I think [Accounts.onCreateUser](http://docs.meteor.com/#/full/accounts_oncreateuser) may be what you are looking for.

**Comment by callmeahab** [comment]
Yeah it is. Thanks.
