### ISSUE TITLE
Relations are not working

### ISSUE THREAD

**Issue by philipheinser** [martijnwalraven/meteor-ios#48]
So far everything is working accept for relations. Relations are always nil for. Should I use a special package on meteor server for relations to work?

**Comment by martijnwalraven** [comment]
No, you don't need to use a special package. But you will have to make sure to either use reference fields with conventional names or customize the mapping.

**Comment by callmeahab** [comment]
You could send related objects from the server with https://github.com/englue/meteor-publish-composite

**Comment by philipheinser** [comment]
I have an optional field createdBy in my application. When I define this das an string in my model and in the datamodel i get as value the id of of the user created this object.
```
 @NSManaged var createdBy: String?

 @NSManaged var createdBy: User?
```
If I switch it two be an User in my model and create a relationship in the datamodel i always get nil for this field.

I also have trouble just declare it as a string because i don't know how to fetch and object by the meteor _id with this framework.

@callmeahab we use this package on the server and in the web this works fine.

**Comment by callmeahab** [comment]
You can send the user object from the server using publishComposite.
Or you can declare a separate field on the object that has createdBy, then fetch the user from the server. To do this you need to subscribe to users collection, then apply a fetch predicate to a fetch request. To get the mongo id of the object you can do `let userId = Meteor.documentKeyForObjectID(user.objectID).documentID as! String`.

**Comment by philipheinser** [comment]
I use publishComposite but it does not work for me with in the iOS app.

**Comment by philipheinser** [comment]
I still try to get the user that belongs to the event. This code crashes when i print the username.
```
if let userKey = event.createdBy {
                    
                    let id = Meteor.objectIDForDocumentKey(METDocumentKey(collectionName: "user", documentID: userKey))
                    let user = Meteor.mainQueueManagedObjectContext.objectWithID(id) as! User
                    print(user.username)
                }
```

**Comment by martijnwalraven** [comment]
Are you sure you're publishing the user? Can you check to see if `user` is nil?

Also, you shouldn't need to manually look up a relationship value. You should be able to just define a `createdBy` relationship in the managed object model and use:
```
@NSManaged var createdBy: User?
```

By default, this will look for a field named `createdById`, but you can customize the mapping.

**Comment by philipheinser** [comment]
How would I customize the mapping?

**Comment by martijnwalraven** [comment]
You can specify a `fieldName` as `userInfo` in the model editor (see Todos example).

**Comment by philipheinser** [comment]
@martijnwalraven Thanks the problem was the default mapping does not apply to our server.
