### ISSUE TITLE
Support for Numtel subscription payloads

### ISSUE THREAD

**Issue by eeekari** [martijnwalraven/meteor-ios#49]
Hi Martijn,
I've been using your DDP Client for the past week and it's just awesome - thanks for putting it out.
I'm currently using it in a project that requires a MySQL database in the back-end, so I've opted to use the popular Numtel package:
https://github.com/numtel/meteor-mysql

This sends some additional JSON through prior (as well as in) subscription payloads. While this isn't an issue with the Client more than it is with the way the Numtel package sends subscription data, I am curious if you or someone else has used the DDP client without having to write a custom JSON serialiser to support this?

Cheers -

**Comment by eeekari** [comment]
Just to clarify, as I've realised my question was worded rather poorly:

In the standard subscription payload, the below JSON is received:
<code>
{
    collection = lists;
    fields =     {
        incompleteCount = 1;
        name = "List O";
    };
    id = MT5DnPfqsLZr9c2HS;
    msg = added;
}
</code>


From the Numtel package, this same JSON data would look like the below:

<code>
{
    collection = lists;
    fields =     {
        diff =         (
                        (
                added,
                                {
                    incompleteCount = 1;
                    name = "List O";
                },
                0
            )
        );
    };
    id = GfBiDhAkLE4PXuFmJ;
    msg = added;
}
</code>

As far as I can tell, handling subscription data from Numtel would only require changing the EJSON parsing. I'd be curious if there is another way around this as my Objective-C skills are shockingly poor.

Cheers -

**Comment by Avtolic** [comment]
It seems that we have the same problem - https://github.com/martijnwalraven/meteor-ios/issues/51

**Comment by eeekari** [comment]
Indeed - I'll close my issue as a duplicate since Martijn has responded on yours.
