### ISSUE TITLE
Can I use SQLite as the database with Core Data?

### ISSUE THREAD

**Issue by sferoze** [martijnwalraven/meteor-ios#50]
I am working with a developer who has never used Meteor before and he is creating the iOS app. He says he has a lot of experience with SQLite. 

Does this package work with SQLite? Any consideration or things to change from the normal if using SQLite?

**Comment by martijnwalraven** [comment]
Meteor iOS uses an in memory cache to store documents received from the server. The easiest way to work with it is through the Core Data integration (which uses a custom NSIncrementalStore subclass, so not the default SQLite storage), but you could certainly access the cache through lower-level APIs yourself (see [here](https://github.com/martijnwalraven/meteor-ios/wiki/Usage-without-Core-Data)). You'd have to handle all synchronization with a SQLite database yourself though.

Hope that answers your question.

**Comment by sferoze** [comment]
@martijnwalraven Thank you it does! But One thing about using without core data doc that confuses me. 

```
- (void)databaseDidChange:(NSNotification *)notification {
  dispatch_async(dispatch_get_main_queue(), ^{
    // If updating the UI, make sure this happens on the main thread
    METDatabaseChanges *databaseChanges = notification.userInfo[METDatabaseChangesKey];
    [databaseChanges enumerateDocumentChangeDetailsUsingBlock:^(METDocumentChangeDetails *documentChangeDetails, BOOL *stop) {
      ...
    }];
  });
}
```

Is this function supposed to automatically re-run anytime the database changes and new info is pushed to the iOS client? 

Also can you please clarify what the `databaseChanges enumerateDocumentChangeDetailsUsingBlock` inside the database change function does?

Basically everything is working so far, but the only confusing part is when data changes in the database, how to detect those changes and sync the changes with SQLite

**Comment by sferoze** [comment]
@martijnwalraven Because we added this function in the view controller and it doesn't seem to be called when we edit the info in the database using the web app

**Comment by martijnwalraven** [comment]
Have you used `NSNotification​Center` to subscribe to `METDatabaseDidChangeNotification` for the `databaseDidChange` method?

**Comment by sferoze** [comment]
Ok that did it! Thank you so much!
