### ISSUE TITLE
Can you use this package with Meteor server deployed with MUP?

### ISSUE THREAD

**Issue by sferoze** [martijnwalraven/meteor-ios#53]
Hi @martijnwalraven 

We tested this package out with our test site hosted at meteor.com 

It works great there. 

I am wondering if it will work the same with a meteor server deployed to linode using MUP?

What about if you use the cluster package?

Does the websocket URL automatically exist?

**Comment by sferoze** [comment]
Also any info that we need when deploying an app using this package to the app store?

**Comment by martijnwalraven** [comment]
It shouldn't matter where your app is deployed, as long as Meteor iOS can keep an open WebSocket connection to the server (it doesn't support SockJS long polling). I'm not familiar with a Meteor Up + Cluster setup, so you should definitely test this yourself. I'm not sure what you mean by 'Does the websocket URL automatically exist?'.

Using Meteor iOS shouldn't affect submission to the App Store. It doesn't use any private APIs.

**Comment by sferoze** [comment]
Thanks I will test with cluster package and let you know.

**Comment by sferoze** [comment]
@martijnwalraven 

I removed the cluster package and deployed my meteor app to linode using MUP

It should act like a normal meteor server, I don't have anything custom setup

It connects to .meteor hosted site just fine

But when I try to connect to the ip address of the server on LiNode (cloud server) I get the error:

```
2015-08-10 21:15:42.732 spiphone[16858:2618522] PSWebSocket: debug mode allowing all SSL certificates
2015-08-10 21:15:42.770 spiphone[16858:2618480] Will retry opening connection after 23.911826 seconds
```

and then it just keeps trying to connect and never connecting.

**Comment by sferoze** [comment]
I figured it out! 

Actually when deploying to linode I dont use the URL

wss://app.url.com/websocket

I had to use

http://app.url.com/websocket

**Comment by sferoze** [comment]
I also just tested with the cluster package and it works like normal! Good stuff
