### ISSUE TITLE
Call method on server and get result back

### ISSUE THREAD

**Issue by thetof91** [martijnwalraven/meteor-ios#57]
Hello

I got a method on server, that gives a result back. And over in my swift project I want to call the method on the server and get the result back from the server, so I can use it in my swift project. 

How do I best do this?

**Comment by pozylon** [comment]
extension Group {
    func enterGroup(finished: (success: Bool)->()) {
        let id : String = Meteor.documentKeyForObjectID(self.objectID).documentID as! String
        
        Meteor.callMethodWithName("enterGroup", parameters: [id]) { (obj, err) -> Void in
            if (err != nil) {
                finished(success: false)
            } else {
                //Kita.invalidateKidsList()
                finished(success: true)
            }
        }
    }

**Comment by thetof91** [comment]
Can you maybe explain it a bit?

I got the method "joinSession" written in meteor on the server, that method give a result back in JSON..

**Comment by pozylon** [comment]
have a look at the wiki, please: https://github.com/martijnwalraven/meteor-ios/wiki/Usage-without-Core-Data, if you have troubles parsing JSON then see http://www.raywenderlich.com/82706/working-with-json-in-swift-tutorial

**Comment by thetof91** [comment]
I will look at it. Thanks for help so far :)

Parse to JSON is not the problem.
