### ISSUE TITLE
Info: Bug in Cordova affects transfer of information from native side to Meteor

### ISSUE THREAD

**Issue by derwaldgeist** [martijnwalraven/meteor-ios#63]
@martijnwalraven: I just wanted to inform you and the Meteor iOS users that I recently found a bug in Apache Cordova (not Meteor iOS) that also affects the transfer of information from the native side to Meteor:

https://issues.apache.org/jira/browse/CB-9485

This bug occurs at a central point, where information is sent back from the native side using the **handleOpenURL** method. Due to a strange behaviour of Apple's NSURL implementation, the URL used to encode the data is being truncated with an ellipsis (...). The Cordova team is not to blame here, I would never have expected Apple's framework to do such weird things...

JesseMacFayden from the Cordova team has now fixed this problem, but as far as I can tell from the Apache JIRA, the fix is planned to be included in the 4.0 version of Cordova. For the meantime, it could be an idea to apply the patch to Meteor's Cordova version manually, as it is just a one-liner.

I am not sure how severe this is for common Meteor iOS usage, but for me, it was a deal breaker, since the information I wanted to deliver to the Meteor side was too long and had been truncated because of this.

**Comment by martijnwalraven** [comment]
Thanks for reporting this, but Meteor iOS is a native framework and does not use Cordova in any way. There is no web view involved so it does not use `handleOpenURL` to transfer information either. 

I think it would be more appropriate to open an issue for this in the main Meteor repository. Unfortunately, I don't think there is much we can do about this ourselves, as we only fork cordova-lib and not the platform-specific projects like cordova-ios.

**Comment by derwaldgeist** [comment]
Ah, I see, I thought this repo was the repo where the iOS side of Meteor's Cordova integration was maintained. Thanks for clarifying this.
