### ISSUE TITLE
Get username from METDocument

### ISSUE THREAD

**Issue by thetof91** [martijnwalraven/meteor-ios#64]
Hello

I got a subscription and get a collection from that.
I can print it out, but only it all. What do I have to do if I just want the like example the username and ip.

    let names = Meteor.database.collectionWithName("users")
    let test = names.documentWithID(Meteor.userID!)
    println("test: \(test)")

And then the print I got is like this

    test: <METDocument key: <collection: users, ID: P2Qq8HQBe3xMj7BxM>, fields: {
    createdAt = "2015-09-09 07:17:13 +0000";
    emails =     (
                {
            address = "test@test.com;
            verified = 0;
        }
    );
    roles =     (
        remote
    );
    services =     {
        password =         {
            bcrypt = "$2a$10$8APGYV9DJwxGHy/UuMDX6esqDhIL1saPZn9C.mQBajjhfAhWwRBwy";
        };
        resume =         {
            loginTokens =             (
                                {
                    hashedToken = "g7Ws6158zbxs+hsM1I94uSIyVLvKwKT1x1hauKbGuyg=";
                    when = "2015-09-09 07:49:49 +0000";
                }
            );
        };
    };
    status =     {
        lastLogin =         {
            date = "2015-09-09 07:49:49 +0000";
            ipAddr = "192.168.100.75";
            userAgent = "<null>";
        };
        online = 0;
    };
    username = test;
    }>

I then want to able to get username and ipAddr out, so I can like set some labels.text to be that.

How do I do this?

**Comment by martijnwalraven** [comment]
A `METDocument` acts like a dictionary, and you could use key-value coding to get the values. But you may prefer to use Core Data or a mapping framework like [Mantle](https://github.com/Mantle/Mantle).

**Comment by thetof91** [comment]
Think found out something

So I can get the username like this

    let username = test["username"] as! String
    self.usernameLabel.text = username

But then when I want ipAddr it should be like this?

    let ipAddr = test["status"]["lastlogin"]["ipAddr"] as! String
    self.ipLabel.text = ipAddr

But then I get this error
Cannot subscript a value of type 'AnyObject?!' with an index of type 'String'

**Comment by martijnwalraven** [comment]
That is one of the downsides of having to deal with an untyped `NSDictionary`. You'll have to cast the result of every subscript to the right type, a nested dictionary in this case. You may also want to read up on the use of optionals in Swift, because forced unwrapping (`!`) is likely to lead to trouble.

The alternative is to stick to key value coding and use something like `user.valueForKeyPath("status.lastlogin.ipAddr")`.
