### ISSUE TITLE
Mapping from subscription to core data entities

### ISSUE THREAD

**Issue by kiwi0r0** [martijnwalraven/meteor-ios#72]
I am trying to use meteor-ios into my project, but I am having issue with how the mapping from subscription to core data actually work.
I have a server with collection:
```
folders
{
     _id: "String",      // mongo generated _id
     folderName: "tutorial",
     description: "This is a folder",
     admin: [                              
          "adminID1",
          "adminID2"
     ]
}
```
and server has `Meteor.publish('folders', function(userID))`

As far as I understand now, `addSubscriptionWithName('folders')` will fill out the managedObjectContext. Then we can do a fetch request to get the content, but to perform fetch, we have to create the corresponding entities and attribute first.

Currently, I have core data set up as:
```
entity name: Folders
entity class: folders
    attribute: id
    attribute: folderName
```
```
override func configureSubscriptionLoader(subscriptionLoader: SubscriptionLoader) {
    subscriptionLoader.addSubscriptionWithName("folders")
}

override func createFetchedResultsController() -> NSFetchedResultsController? {
    let fetchRequest = NSFetchRequest(entityName: "Folders")
    fetchRequest.sortDescriptors = [NSSortDescriptor(key: "folderName", ascending: true)]
    fetchRequest.predicate = nil

    return NSFetchedResultsController(fetchRequest: fetchRequest, managedObjectContext: self.managedObjectContext, sectionNameKeyPath: nil, cacheName: nil)
}
```
But the app terminating with uncaught exception,
```
2015-10-29 14:18:51.145 Clipo App[41394:1121118] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString charValue]: unrecognized selector sent to instance 0xa000000000000301'
```

My question is:
1. When creating core data entities, how should I name its Name and Class (Upper/Lower case, Singular vs. Plural)
2. Do I have to create every attributes for the entities? Or can I just name the ones I need

**Comment by martijnwalraven** [comment]
I've never seen that specific exception, but to answer your questions:
1. Both the entity name and the class should be singular and in camel case.
2. You only have to define the attributes/relationships you need.

Hope that helps!

**Comment by kiwi0r0** [comment]
Thank you for the clarification, I got it to work now. 
As for the exception, apparently xcode saves boolean attribute as `NSNumber`, but the server is trying to set the attribute to boolean and xcode complains. Still looking for a fix right now.
