### ISSUE TITLE
Is there a way to set App Transport Security through Meteor's config files?

### ISSUE THREAD

**Issue by derwaldgeist** [martijnwalraven/meteor-ios#73]
I am using the ```useraccounts:bootstrap``` package in my Cordova app and have noticed that my iOS app cannot connect to the local server for log-in. Tracking down the problem, I found out that the connection is refused because the standard App Transport Security settings do not allow to establish the connection to the Meteor server.

After I manually added this key to my plist file in Xcode, the connection was successful:

```xml
<key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
</key>
```

Is it possible to set this via Meteor's config files so I do not have to remember to set it everytime this setting gets lost?

Another question that is related: I am using some Cordova plugins that require EnableBitcode to be set to false. Is it possible to set this via the Meteor's config files as well?

**Comment by martijnwalraven** [comment]
Meteor 1.2 adds this for you as part of the `com.meteor.cordova-update` plugin. (The actual change to the `plugin.xml` required [is pretty simple](https://github.com/meteor/com.meteor.cordova-update/commit/815f36966f941b153d3979d64a4804064a89c1ba).)

You should be able to override the plugin version on earlier versions of Meteor by adding the plugin manually (`meteor add cordova:com.meteor.cordova-update@https://github.com/meteor/com.meteor.cordova-update/tarball/815f36966f941b153d3979d64a4804064a89c1ba`), but I haven't tested this myself.

**Comment by derwaldgeist** [comment]
Thanks for your quick reply!

**Comment by derwaldgeist** [comment]
Hi Martijn,

I'm still asking myself if it is also possible to set the "Enable Bitcode" build setting somehow, using a Cordova plugin or a configuration file. Can this be achieved as well?

KR, Tom
