### ISSUE TITLE
Is there a reason that sessionId reconnect logic isn't implemented?

### ISSUE THREAD

**Issue by cerupcat** [martijnwalraven/meteor-ios#84]
Is there a reason we don't send sessionId on reconnect? It looks like sessionId isn't really used at all.

**Comment by martijnwalraven** [comment]
Meteor doesn't implement session resumption, so sending `sessionId` on reconnect wouldn't do anything.

**Comment by cerupcat** [comment]
Thanks for the quick response! After looking through the meteor code, I realized that they never actually implemented the sessionId.
